config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'committees/comingsoon'

  get 'committees/unesco'

  get 'committees/nba'

  get 'committees/disec'

  get 'committees/fao'

  get 'committees/legal'

  get 'committees/unsc'

  get 'committees/maumau'

  get 'committees/mormons'

  get 'committees/mexico'

  get 'committees/lenin'

  get 'committees/bangladesh'

  get 'committees/asiafin'

  get 'committees/thailand'

  get 'committees/teutonic'

  get 'committees/hongkong'

  get 'committees/government'

  get 'committees/rebels'

  get 'committees/adhoc'

  get 'adhoc_application' => 'committees#adhoc_application'

  get 'commitees/adhoc_application'

  root 'static_pages#index'

  get 'pdf' => 'static_pages#pdftest'

  get 'home' => 'static_pages#home'
  get 'committees' => 'static_pages#committees'
  get 'sponsors' => 'static_pages#sponsors'
  get 'contact' => 'static_pages#contact'
  get 'venue' => 'static_pages#venue'
  get 'schedule' => 'static_pages#schedule'
  get 'fees' => 'static_pages#fees'
  get 'secretariat' => 'static_pages#secretariat'
  get 'explore' => 'static_pages#explore'
  get 'welcome' => 'static_pages#welcome'
  get 'resources' => 'static_pages#resources'
  get 'munstore' => 'charges#munstore'
  get 'paymentsuccess' => 'static_pages#paymentsuccess'
  get 'hilton' => 'attractions#hilton'
  get 'app_privacy_policy' => 'committees#app_privacy_policy'

  get '/muncharge' => 'charges#muncharge'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'loggedinregistration' => 'users#registrationerror'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :charges
  resources :attractions
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  get 'listofregistrations' => 'users#index'

  get 'conferencepayment' => 'charges#new'
  get 'sponsorship' => 'charges#sponsorship'
  get 'users/:id/balance' => 'users#balance', as: :balance
  get 'users/:id/delegation' => 'users#delegation', as: :delegation
  get 'users/:id/forms' => 'users#forms', as: :forms
  get 'users/:id/settings' => 'users#settings', as: :settings

end

app/models/user.rb
class User < ActiveRecord::Base
  #acts_as_xlsx
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save {self.email = email.downcase }
  before_create :create_activation_digest
  before_update :adjust_balance_if_needed
  validates :name, presence: true, length: { maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: VALID_EMAIL_REGEX}
  validates :delegates_count, presence: true
  validates :university, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true


  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def send_new_registration_email
    UserMailer.new_registration(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def init_balance
    #current_balance.nil? ? self.current_balance = delegates_count * 85 + 90 : current_balance
    #TODO: If charges, change current_balance should be updated
    balance = 0
    charges
    if current_balance.nil?
      charge_list.each do |charge|
        balance += charge[:price] * charge[:quantity]
      end
      self.current_balance = balance
    end
  end

  def initialize_balance
    update_attribute(:amount_paid, 0)
    adjust_balance()
  end

  def adjust_balance_if_needed
    delegates_changed = self.changed.include? "delegates_count"
    balance_not_adjusted = !(self.changed.include? "current_balance")

    if delegates_changed && balance_not_adjusted
       adjust_balance
    end
  end

  def adjust_balance

    current_time = Time.now
    early_fee_time = Time.new(2016, 12, 2)

    if current_time.to_i < early_fee_time.to_i
      balance = 85 + 85 * delegates_count
    else
      balance = 95 + 95 * delegates_count
    end

    balance -= amount_paid

    if !delegate_discount.nil?
      balance -= delegate_discount * delegates_count
    end

    if !delegation_discount.nil?
      balance -= delegation_discount
    end
    balance = calculate_balance_with_stripe_fee(balance)
    update_attribute(:current_balance, balance)
  end

  def charge_list
    current_time = Time.now
    early_fee_time = Time.new(2016, 12, 2)
    default_charge_list = []
    if current_time.to_i < early_fee_time.to_i
      default_charge_list = [ {item: "Delegation Fee--Early",
                            price: 85.00,
                            quantity: 1,
                            date: current_time},
                            {item: "Delegate Fee--Early",
                            price: 85.00,
                            quantity: delegates_count,
                            date: current_time} ]
    else
      default_charge_list = [ {item: "Delegation Fee--Regular",
                            price: 95.00,
                            quantity: 1,
                            date: current_time},
                            {item: "Delegate Fee--Regular",
                            price: 95.00,
                            quantity: delegates_count,
                            date: current_time} ]
    end

    if delegate_discount.nil?
      default_charge_list.push({
        item: "Stripe Transaction Fee (2.9%)",
        price: calculate_stripe_fee(85 + 85*delegates_count),
        quantity: 1,
        date: current_time
        })
    else
      default_charge_list.push({
        item: "Delegate Fee Discount",
        price: (delegate_discount * -1).round(2),
        quantity: delegates_count,
        date: current_time
        })
      default_charge_list.push({
        item: "Stripe Transaction Fee (2.9%)",
        price: calculate_stripe_fee(85 + (85 - delegate_discount) * delegates_count),
        quantity: 1,
        date: current_time
        })
    end

      default_charge_list

  end

  def update_amount_paid(amount)
    update_attribute(:amount_paid, amount_paid + amount)
  end

  def update_balance(amount)
    update_amount_paid(amount)
    set_current_balance(current_balance - amount)
  end

  def get_current_balance
    if current_balance.nil? or !delegate_discount.nil? or !delegation_discount.nil?
      calculate_balance.round(2)
    else
      current_balance.round(2)
    end
    # calculate_balance.round(2)
  end

  def set_current_balance(amount)
    update_attribute(:current_balance, amount)
  end

  def append_charge(charge)
  #  self.charge_list.push(charge)
    charges = charge_list.push(charge)
    self.update_attribute(:charge_list, charges)
  end

  def calculate_balance_with_stripe_fee(balance)
    (balance / 0.97).round(2)
  end

  def calculate_stripe_fee(balance)
    (0.03 / 0.97 * balance).round(2)
  end

  def calculate_balance
    current_time = Time.now.inspect
    early_fee_time = Time.new(2015, 12, 2)
    balance = 95 + 95*delegates_count

    if !delegate_discount.nil?
      balance -= delegate_discount * delegates_count
    end

    if !delegation_discount.nil?
      balance -= delegation_discount
    end
    balance = calculate_balance_with_stripe_fee(balance)
    update_attribute(:current_balance, balance)
    balance
  end

  def set_balance(balance)
    update_attribute(:current_balance, balance)
  end

  def activation_digest=(digest)
    write_attribute(:activation_digest, digest)
  end

  private
    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @user.adjust_balance()
  end

  def new
    if current_user.nil?
      @user = User.new
    else
      redirect_to loggedinregistration_path
    end
  end

  def create
    @user = User.new(user_params)
    begin
      if @user.save
        @user.initialize_balance()
        begin
          @user.send_activation_email
          flash[:info] = "Please check your email to confirm your registration and activate your account."
        rescue Net::SMTPAuthenticationError => e
          puts("ACTIVATION EMAIL ERROR")
          puts(e.backtrace)
          flash[:info] = "Your registration was successful. However, there was an error with sending the email to activate your account. Please email technology@ucbmun.org to activate your account."
        end

        begin
          @user.send_new_registration_email
        rescue Net::SMTPAuthenticationError => error
          puts("REGISTRATION EMAIL ERROR")
          puts(error.backtrace)
        end
        redirect_to root_url
      else
        render 'new'
      end
    rescue ActiveRecord::RecordNotUnique
      @user.errors[:email] = "Address is already associated with a registration."
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])

  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      # if @user.changed == ['delegates_count']
      #   @user.adjust_balance
      # end
      # @user.update_attribute(:current_balance, 1234)
      flash[:success] = "Profile update #{@user.changed}"

      redirect_to @user
    else
      render 'edit'
    end
  end

  def balance
    @user = User.find(params[:id])
    @user.adjust_balance()
  end

  def registrationerror
  end

  def delegation
    @user = User.find(params[:id])

  end


  def index
    @registrations = User.all
    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :university, :password, :password_confirmation,
                                    :username, :phone, :address, :city, :state, :zip, :country, :delegates_count)
    end

        # Before filters

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def send_new_registration_email(user)
    require 'mail'

    options = { :address              => "smtp.gmail.com",
                :port                 => 587,
                :user_name            => ENV['REGISTER_EMAIL'],
                :password             => ENV['REGISTER_PASSWORD'],
                :authentication       => 'plain',
                :enable_starttls_auto => true  }



    Mail.defaults do
      delivery_method :smtp, options
    end

    email_text = "New UCBMUN Registration!

    University: #{user.university}
    Delegates: #{user.delegates_count}
    Name: #{user.name}
    Email: #{user.email}
    Phone: #{user.phone}
    Address: #{user.address}
    #{user.city}, #{user.state} #{user.zip}
    #{user.country}
    Date: #{Time.now.inspect}

    Thanks,
    Steven "


    Mail.deliver do
           to 'registration@ucbmun.org'
         from 'ucbmun.register@gmail.com'
      subject 'New UCBMUN XX Registration'
         body email_text
    end
  end

  def get_full_address(user)
    "#{user.address} \n #{user.city}, #{user.state} #{user.zip} \n #{user.country}"
  end
end

app/views/users/_toolbar.html.erb
<div class="btn-group user-profile-toolbar" role="group" aria-label="...">
  <a href=<%= "/users/#{current_user.id}" %>><button type="button" class="btn btn-default user-profile-button">Profile</button></a>
  <a href=<%=delegation_url(id: current_user.id)%>><button type="button" class="btn btn-default user-profile-button">Delegation</button></a>
  <a href=<%=balance_url(id: current_user.id)%>><button type="button" class="btn btn-default user-profile-button">Finances</button></a>
  <a href=<%=forms_url(id: current_user.id)%>><button type="button" class="btn btn-default user-profile-button">Apps/Resources</button> </a>
  <a href=<%=edit_user_path(current_user) %>><button type="button" class="btn btn-default user-profile-button">Settings</button> </a>
</div>

app/views/users/balance.html.erb
<%= render partial: "toolbar" %>
<h1> Finances </h1>
<div class="balance-main" style="float: left; width: 70%;">
<div class="balance-info" style="width: 90%;">
<h4> Registration fees must be paid within 30 days of registration or reciept of invoice.
  An invoice will be emailed to you within a two days of your registration.
  Fee tiers (early or regular)
  are determined by the date of registration. Payments may be transacted by check, or by credit card online through
  Stripe. Please note that, since Stripe charges a 2.9% transaction fee, online payment adds an additional 2.9% to
  your balance. </h4>

</div>
<h2> Invoice </h2>
<div class="balance-box">
  <table style="margin-left: 30px;">
    <tr style="font-size: 22px; font-weight:bold;">
      <!-- <td style="padding: 10px;"> Date </td> -->
      <td style="padding: 10px;"> Item </td>
      <td style="padding: 10px;"> Qty. </td>
      <td style="padding: 10px;"> Cost </td>
    </tr>
    <% @user.charge_list.each do |charge| %>
      <tr style="font-size: 20px;">
        <!-- <td style="padding: 10px; margin-right: 200px;"> <%= charge[:date] %> -->
        <td style="padding: 10px;"> <%= "#{charge[:item]} @ $#{charge[:price]}" %></td>
        <td style="padding: 10px;"> <%= charge[:quantity] %> </td>
        <td style="padding: 10px;"> <%= "#{charge[:price] * charge[:quantity]}" %></td>
      </tr>
    <% end %>
    <tr style="font-size: 20px;">
      <td style="padding: 10px;"></td>
      <td style="padding: 10px;"></td>
      <td style="padding: 10px;"><%= "$#{@user.get_current_balance}" %></td>
    </tr>
  </table>
<h2> Your balance is: <strong> <%= " $#{@user.get_current_balance}" %> </strong> </h2>

<!-- <a class="btn btn-default" href="/charges/new" role="button">Pay with Stripe!</a> -->
<!-- <a class="btn btn-default" href="#" role="button">Pay with Check!</a> -->
</div>
</div>
<div class="balance-side" style="margin-left: 70%">
  <h3> <strong>Checks Payable To: </strong></h3>
  <h4>ASUC/UCBMUN c/o LEAD Center </h4>
  <h4> 102 Hearst Gym MC 4500 </h4>
  <h4> Berkeley, CA 94720-4500 </h4>
  <h5> *UCBMUN is sponsored by the Associated Students of the University of California, a 501c3 Non-Profit Organization supporting student initiated activities </h5>

  <h3> <strong> Proof of Payment </strong> </h3>
  <p> In order to ease registration and prevent lost checks we ask that you send us Proof of Payment. Proof of Payment can either be a copy or a photo of the completed check or the USPS/UPS/FedEx tracking number, sent electronically to cos-external@ucbmun.org. The Proof of Payment is due within 20 days of Early or Regular registration (and before BayMUN if you wish to attend), and definitely within 7 days of the last registration date. If you fail to send Proof of Payment by that date and have not communicated with our Chief of Staff External, you will not be allowed to participate in UCBMUN XXI. In case of special circumstances, please contact our Chief of Staff - External.</p>
</div>

app/views/users/delegation.html.erb
<%= render partial: "toolbar" %>
<h2> Delegation </h2>
<h3> You have registered <strong> <%= "#{@user.delegates_count} delegates." %> </strong> </h3>
<h4> To change your delegation numbers, please go to Settings. </h4>
<!-- <h4> Please submit your committee preferences <a href = "http://goo.gl/forms/EsymrqicSm">here</a> or below! </h4>
<iframe src="http://goo.gl/forms/EsymrqicSm" style="width: 800px; height: 800px;"></iframe> -->

app/views/users/edit.html.erb
<h1> Update your Information </h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
     <%= render 'shared/error_messages'%>

     <%= f.label :name %>
     <%= f.text_field :name, class: 'form-control' %>

     <%= f.label :university %>
     <%= f.text_field :university, class: 'form-control' %>

     <%= f.label :email %>
     <%= f.email_field :email, class: 'form-control' %>

     <%= f.label :username %>
     <%= f.text_field :username, class: 'form-control' %>

     <%= f.label :password %>
     <%= f.password_field :password, class: 'form-control' %>

     <%= f.label :password_confirmation, "Confirmation"%>
     <%= f.password_field :password_confirmation, class: 'form-control' %>

     <%= f.label :phone %>
     <%= f.text_field :phone, class: 'form-control' %>

     <%= f.label :address %>
     <%= f.text_field :address, class: 'form-control' %>

     <%= f.label :city %>
     <%= f.text_field :city, class: 'form-control' %>

     <%= f.label :state %>
     <%= f.text_field :state, class: 'form-control' %>

     <%= f.label :zip %>
     <%= f.text_field :zip, class: 'form-control' %>

     <%= f.label :country %>
     <%= f.text_field :country, class: 'form-control' %>

     <%= f.label :delegates_count %>
     <%= f.number_field :delegates_count, class: 'form-control' %>

     <%= f.submit "Save Changes", class: "btn btn-primary" %>
    <%end%>
  </div>
</div>

app/views/users/forms.html.erb
<%= render partial: "toolbar" %>
<h2> Applications and Resources </h2>
<ul>
  <li><h5> <a href="/UCBMUN_rules_and_procedures.pdf"> UCBMUN XX Rules and Procedures </a> </h5></li>
  <li><h5> <a href="https://goo.gl/forms/RGNg7vUSKuLkE62H3"> Adhoc Committee Application </a> </h5></li>
</ul>

app/views/users/index.html.erb
<%= link_to "Download as Excel", users_path(format: "xlsx") %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3" style="margin-bottom: 40px;">
    <h1 style="text-align: center; font-family: 'code-light';"> REGISTER </h1>
    <%= form_for(@user) do |f| %>
     <%= render 'shared/error_messages'%>

     <%= f.label :name, class: "form-label" %>
     <%= f.text_field :name, class: 'form-control' %>

     <%= f.label :university, class: "form-label" %>
     <%= f.text_field :university, class: 'form-control' %>

     <%= f.label :email, class: "form-label" %>
     <%= f.email_field :email, class: 'form-control' %>

     <%= f.label :username, class: "form-label" %>
     <%= f.text_field :username, class: 'form-control' %>

     <%= f.label :password, class: "form-label" %>
     <%= f.password_field :password, class: 'form-control' %>

     <%= f.label :password_confirmation, "Confirmation", class: "form-label"%>
     <%= f.password_field :password_confirmation, class: 'form-control' %>

     <%= f.label :phone, class: "form-label" %>
     <%= f.text_field :phone, class: 'form-control' %>

     <%= f.label :address, class: "form-label" %>
     <%= f.text_field :address, class: 'form-control' %>

     <%= f.label :city, class: "form-label" %>
     <%= f.text_field :city, class: 'form-control' %>

     <%= f.label :state, class: "form-label" %>
     <%= f.text_field :state, class: 'form-control' %>

     <%= f.label :zip, class: "form-label" %>
     <%= f.text_field :zip, class: 'form-control' %>

     <%= f.label :country, class: "form-label" %>
     <%= f.text_field :country, class: 'form-control' %>

     <%= f.label :delegates_count, class: "form-label" %>
     <%= f.number_field :delegates_count, class: 'form-control' %>

     <%= f.submit "Register for UCBMUN XXI", class: "btn btn-primary" %>
    <%end%>
  </div>
</div>

app/views/users/registrationerror.html.erb
<h1> Error: Please logout of your current account before registering a new account. </h1>

app/views/users/settings.html.erb
<%= render partial: "toolbar" %>
<h2> Settings </h2>
<h3> Coming soon. </h3>

app/views/users/show.html.erb
<%= render partial: "toolbar" %>
<div class="row">
<div class="profile-left col-md-7 cold-md-offset-1">
  <div class="user-profile-welcome">
    <h2> Welcome, </h2>
    <h2> <%= @user.university %> !</h2>
  </div>

  <div class="user-profile-news">
  </div>
</div>

<div class="profile-right col-md-3 col-md-offset-1">
  <div class="user-profile-sidebar">
    <div class="user-profile-pic-wrapper">
      <%= image_tag "no_photo_person.png", class: "user-profile-pic" %>
    </div>
    <div class="user-profile-info" >
      <h4><%= @user.name %> </h4>
      <h5> <%=@user.email %> </h5>
      <h5> <%= @user.university %> </h5>
      <h6> <%=@user.address %> </h6>
      <h6> <%="#{@user.city}, #{@user.state} #{@user.zip}"%></h6>
      <h6> <%=@user.country %> </h6>
    </div>
  </div>
</div>
</div>