config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'committees/comingsoon'

  get 'committees/unesco'

  get 'committees/nba'

  get 'committees/disec'

  get 'committees/fao'

  get 'committees/legal'

  get 'committees/unsc'

  get 'committees/maumau'

  get 'committees/mormons'

  get 'committees/mexico'

  get 'committees/lenin'

  get 'committees/bangladesh'

  get 'committees/asiafin'

  get 'committees/thailand'

  get 'committees/teutonic'

  get 'committees/hongkong'

  get 'committees/government'

  get 'committees/rebels'

  get 'committees/adhoc'

  get 'adhoc_application' => 'committees#adhoc_application'

  get 'commitees/adhoc_application'

  root 'static_pages#index'

  get 'pdf' => 'static_pages#pdftest'

  get 'home' => 'static_pages#home'
  get 'committees' => 'static_pages#committees'
  get 'sponsors' => 'static_pages#sponsors'
  get 'contact' => 'static_pages#contact'
  get 'venue' => 'static_pages#venue'
  get 'schedule' => 'static_pages#schedule'
  get 'fees' => 'static_pages#fees'
  get 'secretariat' => 'static_pages#secretariat'
  get 'explore' => 'static_pages#explore'
  get 'welcome' => 'static_pages#welcome'
  get 'resources' => 'static_pages#resources'
  get 'munstore' => 'charges#munstore'
  get 'paymentsuccess' => 'static_pages#paymentsuccess'
  get 'hilton' => 'attractions#hilton'
  get 'app_privacy_policy' => 'committees#app_privacy_policy'

  get '/muncharge' => 'charges#muncharge'

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  get 'loggedinregistration' => 'users#registrationerror'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users
  resources :charges
  resources :attractions
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  get 'listofregistrations' => 'users#index'

  get 'conferencepayment' => 'charges#new'
  get 'sponsorship' => 'charges#sponsorship'
  get 'users/:id/balance' => 'users#balance', as: :balance
  get 'users/:id/delegation' => 'users#delegation', as: :delegation
  get 'users/:id/forms' => 'users#forms', as: :forms
  get 'users/:id/settings' => 'users#settings', as: :settings

end

app/views/layouts/_footer.html.erb
<div class="container-fluid footer" style="background-color: #7D9EB2;">
  <p> Designed by Tim Guan. Developed by Steven Chen. </p>
</div>

app/views/layouts/_header.html.erb
<div class="nav-container">
  <div id="navigation" class="nav-bar-active" style="position: static; background-color: #152c6d; padding-top: 0;">
    <!-- To prevent overlapping, delete absolute from logo_container, this will mess up some of the
    nav-bar transitions -->
    <ul class="logo_container">
      <div class="logo" style="margin-top: 6px;">
        <%= image_tag "icons/ucbmun_logo.png", style: "height: 40px;"%>
      </div>
      <div class="ucbmun-header", style = "margin: 6px; font-size: 30px;">
        UCBMUN XXI
      </div>
    </ul>

    <div class="secretariat-title" id="secretariat-title">
      Meet the Secretariat
    </div>
    <div class="ob-title" id="ob-title">
      Meet the Officer's Board
    </div>
    <div class="sb-title" id="sb-title">
      Specialized Bodies
    </div>
    <div class="cc-title" id="cc-title">
      Crisis Committees
    </div>
    <div class="jcc-title" id="jcc-title">
      Joint Crisis Committees
    </div>
    <div class="welcome-title" id="welcome-title">
      Welcome Letter
    </div>
    <div class="logistics-title" id="logistics-title">
      Logistics
    </div>
    <div class="sponsor-title" id="sponsor-title">
      Sponsors
    </div>
    <div class="instagram-title" id="instagram-title">
      #UCBMUN <!--<img src="./images/instagram.png" style="height:19px;">-->
    </div>
    <div class="explore-title" id="explore-title">
      Explore SF
    </div>

    <ul class="links-active" id="links">
      <li class="home-link link underline" data-menuanchor="home">
          <a href="/#home">
            Home
          </a>
      </li>
      <li class="about-link link" data-menuanchor="about">
        <a href="/#about/0">
          About Us
        </a>
      </li>
      <li class="committee-link link" data-menuanchor="committee">
        <a href="/#committee/0">
          Committees
        </a>
      </li>


      <li class="info-link link" data-menuanchor="info">
        <a href="/#info/0">
          Information
        </a>
      </li>
      <li class="attraction-link link" data-menuanchor="attraction">
        <a href="/#attraction/0">
          Attractions
        </a>
      </li>
      <% if !logged_in? %>
      <li class="apply-link link">
          <%= link_to "Register | Log In", login_path %>
      </li>
      <% else %>
      <li class="apply-link link">
          <%= link_to "Log Out", logout_path, method: :delete %>
      </li>
      <% end %>

  </div>
</div>

app/views/layouts/_header_original.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><%= image_tag "logo_no_text.png", class: "logo-header img-responsive"%></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-conference">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Conference<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Welcome Letter", welcome_path %></li>
            <li><%= link_to "Venue", venue_path(@user) %></</li>
            <li><%= link_to "Schedule", schedule_path %></li>
            <li><%= link_to "Fee Information", fees_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Secretariat", secretariat_path %></li>
            <li><%= link_to "Explore SF!", explore_path %></li>
            <li><%= link_to "Resources", resources_path %></li>

          </ul>
        </li>
        <li><%= link_to "Committees", committees_path %></li>
        <li><%= link_to "Sponsors", sponsors_path %></li>
        <li><%= link_to "Contact Us", contact_path %></li>
        <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Balance", balance_url(id: current_user.id) %></li>
            <li><%= link_to "Apps/Forms", current_user %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log out", logout_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_navbar.html.erb
<div class="nav-container">
  <div id="navigation" class="nav-bar-active">
    <!-- To prevent overlapping, delete absolute from logo_container, this will mess up some of the
    nav-bar transitions -->
    <ul class="logo_container">
      <div class="logo">
        <%= image_tag "icons/ucbmun_logo.png" %>
      </div>
      <div class="ucbmun">
        UCBMUN XXI
      </div>
    </ul>

    <div class="secretariat-title" id="secretariat-title">
      Meet the Secretariat
    </div>
    <div class="ob-title" id="ob-title">
      Meet the Officer's Board
    </div>
    <div class="sb-title" id="sb-title">
      Specialized Bodies
    </div>
    <div class="cc-title" id="cc-title">
      Crisis Committees
    </div>
    <div class="jcc-title" id="jcc-title">
      Joint Crisis Committees
    </div>
    <div class="welcome-title" id="welcome-title">
      Welcome Letter
    </div>
    <div class="logistics-title" id="logistics-title">
      Logistics
    </div>
    <div class="sponsor-title" id="sponsor-title">
      Sponsors
    </div>
    <div class="explore-title" id="explore-title">
      Explore SF
    </div>
    <div class="instagram-title" id="instagram-title">
      #UCBMUN <!--<img src="./images/instagram.png" style="height:19px;">-->
    </div>

    <ul class="links-active" id="links">
      <li class="home-link link underline" data-menuanchor="home">
          <a href="#home">
            Home
          </a>
      </li>
      <li class="about-link link" data-menuanchor="about">
        <a href="#about/0">
          About Us
        </a>
      </li>
      <li class="committee-link link" data-menuanchor="committee">
        <a href="#committee/0">
          Committees
        </a>
      </li>


      <li class="info-link link" data-menuanchor="info">
        <a href="#info/0">
          Information
        </a>
      </li>
      <li class="attraction-link link" data-menuanchor="attraction">
        <a href="#attraction/0">
          Attractions
        </a>
      </li>
      <% if !logged_in? %>
      <li class="apply-link link">
          <%= link_to "Register | Log In", login_path %>
      </li>
      <% else %>
      <li class="apply-link link">
          <%= link_to "Log Out", logout_path, method: :delete %>
      </li>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag %>
  <title>UC Berkeley Model United Nations Collegiate Conference</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="description"
    content="UCBMUN XXI, the collegiate conference for UC Berkeley Model United Nations will be held from March 3rd to March 5th, 2017.
             Come join us in beautiful San Francisco, California at the Hilton Hotel in the Financial District. Registration is now open,
             and the early registration deadline is by November 30th. Register now!">
</head>
<body>
  <%= render 'layouts/header' %>
  <!-- <div class=<%=@container_type.nil? ? "container" : @container_type %>> -->
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <br></br>
    <br></br>
    <%= yield %>
    <% if !@container_type.nil? and @container_type != "home-page"%>
    <br></br>
    <% end %>
    <!--<%= debug(params) if Rails.env.development? %> -->
  <!-- </div> -->

  <!-- <%= render 'layouts/footer' %> -->
</body>
</html>

app/views/layouts/attractions.html.erb
<%= yield %>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag %>
  <title>UCBMUN XXI</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class = "container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/layouts/committees.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag %>
  <title>UCBMUN XXI</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <!-- <div class=<%=@container_type.nil? ? "container" : @container_type %>> -->
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <% if !@container_type.nil? and @container_type != "home-page"%>
    <br></br>
    <% end %>
    <!--<%= debug(params) if Rails.env.development? %> -->
  <!-- </div> -->

  <!-- <%= render 'layouts/footer' %> -->
</body>
</html>

app/views/layouts/committees1.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UCBMUN XXI</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class=<%= "committee-background #{@committee_name}-background-image">
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/static_pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag %>
  <title>UC Berkeley Model United Nations Collegiate Conference</title>
  <%= stylesheet_link_tag    'application' %>
  <!-- <%= stylesheet_link_tag    'jquery.fullPage.css' %>
  <%= stylesheet_link_tag    'style.css' %> -->
  <%= javascript_include_tag 'application' %>
  <!-- <%= javascript_include_tag 'scrolloverflow.min.js' %>
  <%= javascript_include_tag 'jquery.fullPage.js' %>
  <%= javascript_include_tag 'script' %> -->
  <%= csrf_meta_tags %>
  <meta name="description"
    content="UCBMUN XXI, the collegiate conference for UC Berkeley Model United Nations will be held from March 3rd to March 5th, 2017.
             Come join us in beautiful San Francisco, California at the Hilton Hotel in the Financial District. Registration is now open,
             and the early registration deadline is by November 30th. Register now!">
</head>
<body>
  <%= render "layouts/navbar" %>
  <%= yield %>
</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag %>
  <title>UCBMUN XXI</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="description"
    content="UCBMUN XXI, the collegiate conference for UC Berkeley Model United Nations will be held from March 3rd to March 5th, 2017.
             Come join us in beautiful San Francisco, California at the Hilton Hotel in the Financial District. Registration is now open,
             and the early registration deadline is by November 30th. Register now!">
</head>
<body style="font-family: 'Raleway'">
  <%= render 'layouts/header' %>
  <!-- <div class=<%=@container_type.nil? ? "container" : @container_type %>> -->
  <div class = "container">
      <br></br>
      <br></br>
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
    <%= yield %>


    <!--<%= debug(params) if Rails.env.development? %> -->
  </div>

  <!-- <%= render 'layouts/footer' %> -->
</body>
</html>